%% review_computed_outputs.m
% Review computed GPCR and marker outputs generated by Python.
% Use MATLAB for quick visualization and sanity checks; use Python for Allen data extraction.

clear; clc;

baseDir = "F:\Allen_ABC_Project\output\final";
gpcrFile = fullfile(baseDir, "Allen_GPCR_Ranking.csv");

if ~isfile(gpcrFile)
    error("Cannot find Allen_GPCR_Ranking.csv. Update baseDir or run Python pipeline first.");
end

G = readtable(gpcrFile, 'TextType','string');
disp(size(G));
disp(G.Properties.VariableNames');

% Basic sanity check
if all(ismember(["gpcr_gene","mean_log2_expr","pct_expr"], string(G.Properties.VariableNames)))
    figure('Color','w');
    scatter(G.pct_expr, G.mean_log2_expr, 12, 'filled');
    xlabel('% expressing cells');
    ylabel('Mean log2 expression');
    title('Computed GPCR expression summary');
    grid on;
    saveas(gcf, fullfile(baseDir, "GPCR_expression_vs_pctexpr.png"));
end

% Top GPCRs overall
G = sortrows(G, "mean_log2_expr", "descend");
disp(G(1:min(30,height(G)), :));
